
#include <libkorutin.h>

#ifdef KORO_BACKEND_CONTEXT

#include "backend.h"
#include <assert.h>

// -------------------------------------------------------------------------------------- boost fcontext

// This based on Boost Context library by Oliver Kowalke
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

typedef void * fcontext_t;

typedef struct
{
  fcontext_t fctx;
  void * data;
} transfer_t;

fcontext_t make_fcontext(void * sp, size_t size, void (*fn)(transfer_t));
transfer_t jump_fcontext(fcontext_t const to, void * vp);
//transfer_t ontop_fcontext(fcontext_t const to, void * vp, transfer_t (*fn)(transfer_t));

// --------------------------------------------------------------------------------------

static void _executor(transfer_t t)
{
  koro_t * h = (koro_t*)t.data;
  assert(h != NULL);

  h->b = (uintptr_t)t.fctx;
  h->fn(h->ctx);
  h->finished = true;
  jump_fcontext((fcontext_t)h->b, NULL);
}

void _koro_backend_init(koro_t * h)
{
  if(!h)
    return;

  size_t stack_size = (uint8_t*)h->stack_start - (uint8_t*)h->stack_end;
  h->a = (uintptr_t)make_fcontext(h->stack_start, stack_size, _executor);
}

void _koro_run(koro_t * h)
{
  if(!h || h->finished)
    return;

  h->a = (uintptr_t)jump_fcontext((fcontext_t)h->a, h).fctx;
}

void _koro_yield(koro_t * h)
{
  if(!h)
    return;

  h->b = (uintptr_t)jump_fcontext((fcontext_t)h->b, NULL).fctx;
}

#endif
